### ISSUE TITLE
Discrepancy in general.php's location

### ISSUE THREAD

**Issue by ghost** [40Digits/craft-boilerplate#1]
<img width="655" alt="screen shot 2016-03-04 at 9 31 00 pm" src="https://cloud.githubusercontent.com/assets/11316277/13545422/87508bf0-e250-11e5-8c80-5187e971f2dc.png">
<img width="533" alt="screen shot 2016-03-04 at 9 31 17 pm" src="https://cloud.githubusercontent.com/assets/11316277/13545423/8d0a0b8e-e250-11e5-827b-d5b92538be0c.png">

<img width="284" alt="screen shot 2016-03-04 at 9 32 42 pm" src="https://cloud.githubusercontent.com/assets/11316277/13545424/a78871ee-e250-11e5-8d1f-6348d8180329.png">

There seems to be an error in the `npm run update-craft` or in the SETUP.md's instructions.
As the script runs, it read `inflating: tmp/craft/config/general.php`, yet the command within the SETUP.md files reads `cp craft/config/local/general.example.php craft/config/local/general.php`.

I provided an image of the resulting directory structure for aid.

**Comment by hahnzilla** [comment]
Talked with @miguelsolano about this. I can't remember why it's resolved, but I know it's resolved... I think it was just a silly misread at a god awful hour of the night.
