### ISSUE TITLE
Can we add a step by step for setting up a dev env through homestead for craft?

### ISSUE THREAD

**Issue by ghost** [40Digits/craft-boilerplate#2]
I just ran through a local install and ended up missing a dependency called mcrypt. Needless to say, I spent around an hour trying to resolve and fix it. Finally, I had the project set up and decided to try homestead. I ran homestead and provisioned the box, added the database, and finally ran homestead up, after less than 5 mins I had a stable dev environment. Should we encourage people to use homestead? Should we include a HOMESTEAD.md ?

**Comment by besimhu** [comment]
Yes, mcrypt can take a long time to get working. Arob had a similar issue, and I was going to document the fix, however with him there was something else that was throwing it all off. It's been well over 2 years now since I had it installed, so I don't recall any issues that I ran into. 

On it's own, the mcrypt install is fairly simple. The issue stems down to hooking it all up whether they are using brew or native PHP.

Have not tried homestead.

**Comment by hahnzilla** [comment]
This would be a good time to introduce vagrant. @miguelsolano you're in charge of getting a vagrant box up and running for testing.

**Comment by ghost** [comment]
@dhahn I know we already talked about this, but I think it'd be beneficial to list of the preliminary thoughts that we had concerning employing ansible: 

## #1) Where does the DB reside? 

Considering that we will create a vagrant box for each one of our projects, where do we want to host our dbs? Do we want to pull from dev? Could we automate this? Should we point them at our local machines? 

## #2) How maintainable is this solution? 

What does the size of the vagrant box mean for the dev that has to work on a few projects? Will they be too large for their memory limit? 

## #3) Do we want to continue to promote threepio or do we discard this for the ansible .j2 templates?

I'm in favor of using the ansible .j2 templates. Why program a whole module to do what a few simple lines of an ansible playbook(script) can do? Furthermore, setting up threepio and configuring it seems like a lot of over head. As well, if we do decide to continue with ansible for configuring more than our local environments, we could potentially run a command that sets this vhost on dev and prod programmatically by sshing in. 

## #4) Should this be tied to the Craft-boilerplate repo or should this be moved out to its own repo? 

Unless we are going to have a single repo where we place all our ansible playbooks(scripts), I do not see why it shouldn't live in with the craft-boilerplate repo. These playbooks(scripts) are meant to be specific to each project. For example, if we want to set a node project up, we will have a node ansible playbook, if we want a ruby project we'll have a ruby ansible. These playbooks can be borrowed from, but they shouldn't be copied. They are meant to be somewhere between project specific and project agnostic. I'd say they should be platform specific. 

## #5) Any objections to vagrant in general? 

????????

Feel free to reply, disagree, or simply brainstorm. Just wanting to keep the conversation going.

**Comment by hahnzilla** [comment]
#1) I think it makes sense to keep the db local to the computer. Although, it'd be nice to see how easy it is to switch from project to project with the db being hosted on the vagrantbox. 

#2) It should be fine... should be, but yes let's test with multiple apps running and see if there are any painpoints

#3) threepio doesn't make sense in this context

#4) I think you won me over with keeping it in this repo. Let's get it up and running and see how it works from there.

#5) not at the moment :) 

#6) I'm moving these to separate issues that link to a milestone. If you create any future issues concerning ansible make sure to tag them with the Ansible Milestone.
