### ISSUE TITLE
Can we get a process of continually amending the wiki as we continue? 

### ISSUE THREAD

**Issue by ghost** [40Digits/craft-boilerplate#4]
I think it'd be a great idea to start filling up the wiki, I am aware that this will probably be an after hours task or when you have absolutely nothing to do, but it'd be great to have a wiki setup.

**Comment by hahnzilla** [comment]
I appoint you Lord of the Wiki. May you reign with supreme benevolence and wisdom

**Comment by ghost** [comment]
Got it Jefe
