### ISSUE TITLE
 Do we want to continue to promote threepio or do we discard this for the ansible .j2 templates?

### ISSUE THREAD

**Issue by hahnzilla** [40Digits/craft-boilerplate#7]
I'm in favor of using the ansible .j2 templates. Why program a whole module to do what a few simple lines of an ansible playbook(script) can do? Furthermore, setting up threepio and configuring it seems like a lot of over head. As well, if we do decide to continue with ansible for configuring more than our local environments, we could potentially run a command that sets this vhost on dev and prod programmatically by sshing in.

**Comment by besimhu** [comment]
+1
